-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.add_on_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audit_session_id uuid NOT NULL,
  location_id integer NOT NULL,
  brand character varying NOT NULL,
  item_name character varying NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  reason text NOT NULL,
  cost_price numeric,
  selling_price numeric,
  image_url text,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  reported_by uuid NOT NULL,
  reported_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT add_on_items_pkey PRIMARY KEY (id),
  CONSTRAINT add_on_items_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT add_on_items_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT add_on_items_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT add_on_items_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  location_id integer NOT NULL,
  total_rack_count integer NOT NULL DEFAULT 0,
  status USER-DEFINED DEFAULT 'active'::audit_status,
  started_at timestamp with time zone DEFAULT now(),
  started_by uuid,
  completed_at timestamp with time zone,
  completed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  shortname character varying NOT NULL,
  CONSTRAINT audit_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT audit_sessions_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id),
  CONSTRAINT audit_sessions_started_by_fkey FOREIGN KEY (started_by) REFERENCES public.users(id),
  CONSTRAINT audit_sessions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.damage_drafts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_session_id uuid NOT NULL,
  barcode character varying NOT NULL,
  damage_severity USER-DEFINED DEFAULT 'medium'::damage_severity_enum,
  damage_description text,
  photos_completed boolean DEFAULT false,
  imported_by uuid,
  imported_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  converted_to_damage_id uuid,
  CONSTRAINT damage_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT damage_drafts_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT damage_drafts_converted_to_damage_id_fkey FOREIGN KEY (converted_to_damage_id) REFERENCES public.damaged_items(id),
  CONSTRAINT damage_drafts_imported_by_fkey FOREIGN KEY (imported_by) REFERENCES public.users(id)
);
CREATE TABLE public.damage_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  damaged_item_id uuid NOT NULL,
  image_url text NOT NULL,
  image_filename character varying NOT NULL,
  image_order integer NOT NULL CHECK (image_order >= 1 AND image_order <= 3),
  file_size_bytes integer,
  mime_type character varying DEFAULT 'image/jpeg'::character varying,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT damage_images_pkey PRIMARY KEY (id),
  CONSTRAINT damage_images_damaged_item_id_fkey FOREIGN KEY (damaged_item_id) REFERENCES public.damaged_items(id)
);
CREATE TABLE public.damaged_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_session_id uuid NOT NULL,
  barcode character varying NOT NULL,
  reported_by uuid NOT NULL,
  reported_at timestamp with time zone DEFAULT now(),
  damage_description text,
  damage_severity USER-DEFINED DEFAULT 'medium'::damage_severity_enum,
  status USER-DEFINED DEFAULT 'pending'::damage_status_enum,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  removed_from_stock boolean DEFAULT false,
  removed_at timestamp with time zone,
  removed_by uuid,
  estimated_loss_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT damaged_items_pkey PRIMARY KEY (id),
  CONSTRAINT damaged_items_removed_by_fkey FOREIGN KEY (removed_by) REFERENCES public.users(id),
  CONSTRAINT damaged_items_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT damaged_items_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT damaged_items_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_id integer NOT NULL,
  item_code text NOT NULL,
  brand text NOT NULL,
  item_name text NOT NULL,
  expected_quantity integer NOT NULL DEFAULT 0,
  unit_cost numeric NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.locations (
  id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass),
  name character varying NOT NULL,
  address text,
  city character varying,
  state character varying,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying DEFAULT 'info'::character varying,
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.partial_damages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scan_id uuid,
  audit_session_id uuid NOT NULL,
  rack_id uuid,
  barcode text NOT NULL,
  damage_type text NOT NULL CHECK (damage_type = ANY (ARRAY['incomplete_set'::text, 'partial_damage'::text, 'quality_issue'::text, 'packaging_issue'::text, 'other'::text])),
  affected_units integer,
  total_units integer,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['minor'::text, 'moderate'::text, 'severe'::text])),
  remarks text NOT NULL,
  photo_urls ARRAY,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT partial_damages_pkey PRIMARY KEY (id),
  CONSTRAINT partial_damages_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT partial_damages_scan_id_fkey FOREIGN KEY (scan_id) REFERENCES public.scans(id),
  CONSTRAINT partial_damages_rack_id_fkey FOREIGN KEY (rack_id) REFERENCES public.racks(id),
  CONSTRAINT partial_damages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.racks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_session_id uuid NOT NULL,
  rack_number character varying NOT NULL,
  shelf_number character varying,
  location_id integer NOT NULL,
  status USER-DEFINED DEFAULT 'available'::rack_status,
  scanner_id uuid,
  assigned_at timestamp with time zone,
  completed_at timestamp with time zone,
  ready_for_approval boolean DEFAULT false,
  ready_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  barcode character varying,
  CONSTRAINT racks_pkey PRIMARY KEY (id),
  CONSTRAINT racks_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT racks_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT racks_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.users(id),
  CONSTRAINT racks_scanner_id_fkey FOREIGN KEY (scanner_id) REFERENCES public.users(id),
  CONSTRAINT racks_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.scans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_session_id uuid NOT NULL,
  rack_id uuid NOT NULL,
  barcode character varying NOT NULL,
  scanner_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  manual_entry boolean DEFAULT false,
  notes text,
  device_id character varying,
  scanned_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  client_scan_id text UNIQUE,
  CONSTRAINT scans_pkey PRIMARY KEY (id),
  CONSTRAINT scans_scanner_id_fkey FOREIGN KEY (scanner_id) REFERENCES public.users(id),
  CONSTRAINT scans_audit_session_id_fkey FOREIGN KEY (audit_session_id) REFERENCES public.audit_sessions(id),
  CONSTRAINT scans_rack_id_fkey FOREIGN KEY (rack_id) REFERENCES public.racks(id)
);
CREATE TABLE public.sync_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id character varying NOT NULL,
  data_type character varying NOT NULL CHECK (data_type::text = ANY (ARRAY['scan'::character varying, 'rack_update'::character varying, 'user_action'::character varying]::text[])),
  payload jsonb NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  retry_count integer DEFAULT 0,
  error_message text,
  created_at timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone,
  CONSTRAINT sync_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'scanner'::user_role,
  location_ids ARRAY DEFAULT '{}'::integer[],
  active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  username character varying NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users_backup_pre_migration (
  id uuid,
  email character varying,
  full_name character varying,
  role character varying,
  location_ids ARRAY,
  device_id character varying,
  active boolean,
  last_login timestamp without time zone,
  created_at timestamp without time zone,
  updated_at timestamp without time zone,
  username character varying,
  has_password boolean,
  password_hash text
);